[package]
name = "terminal"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "terminal"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
crossterm = "0.28"
ratatui = "0.29"
rustler = "0.35.0"

[profile.release]
codegen-units = 1
lto = true
